// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'run `flutterfire configure` to generate real values.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6iJExHki2XjgUwpPzXLvb-YybpMTD4K8',
    appId: '1:137120787865:web:c4fe8a0d9e13513355f708',
    messagingSenderId: '137120787865',
    projectId: 'to-do-app-f37b2',
    authDomain: 'to-do-app-f37b2.firebaseapp.com',
    storageBucket: 'to-do-app-f37b2.firebasestorage.app',
    measurementId: 'G-P8CHW65C96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZIFAFS9RWY7JRlG0nEnRaYsOtE29HncA',
    appId: '1:137120787865:android:f9b3e331e111400155f708',
    messagingSenderId: '137120787865',
    projectId: 'to-do-app-f37b2',
    storageBucket: 'to-do-app-f37b2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkleQV0bKmROrY2h0EWNazwiWgPRRP_Wc',
    appId: '1:137120787865:ios:b0765838f9e0926b55f708',
    messagingSenderId: '137120787865',
    projectId: 'to-do-app-f37b2',
    storageBucket: 'to-do-app-f37b2.firebasestorage.app',
    iosBundleId: 'com.example.simpleTodoApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkleQV0bKmROrY2h0EWNazwiWgPRRP_Wc',
    appId: '1:137120787865:ios:b0765838f9e0926b55f708',
    messagingSenderId: '137120787865',
    projectId: 'to-do-app-f37b2',
    storageBucket: 'to-do-app-f37b2.firebasestorage.app',
    iosBundleId: 'com.example.simpleTodoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6iJExHki2XjgUwpPzXLvb-YybpMTD4K8',
    appId: '1:137120787865:web:00928eb0b3994dda55f708',
    messagingSenderId: '137120787865',
    projectId: 'to-do-app-f37b2',
    authDomain: 'to-do-app-f37b2.firebaseapp.com',
    storageBucket: 'to-do-app-f37b2.firebasestorage.app',
    measurementId: 'G-9ZLFGBXV0Q',
  );
}
